# Generated by Django 3.2 on 2021-04-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_movie_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avg_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Средняя оценка'),
        ),
    ]
