# Generated by Django 3.2 on 2021-05-11 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_movie_avg_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('id',), 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelManagers(
            name='movie',
            managers=[
            ],
        ),
    ]
