# Generated by Django 3.2 on 2021-05-13 16:38

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210513_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload.movie_image_directory_path, validators=[utils.validators.validate_size, utils.validators.validate_extension]),
        ),
        migrations.AlterField(
            model_name='producer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload.producer_image_directory_path, validators=[utils.validators.validate_size, utils.validators.validate_extension]),
        ),
    ]
