# Generated by Django 3.2 on 2021-05-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210513_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avg_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Средняя оценка'),
        ),
    ]
