# Generated by Django 3.2 on 2021-05-13 13:20

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0002_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user', validators=[utils.validators.validate_size, utils.validators.validate_extension]),
        ),
    ]
